name: Go

on:
  push:
    branches: [main, golang-rewrite]
  pull_request:
    branches: [main, golang-rewrite]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        go-version: ["1.23"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Go dependencies
        run: go mod download
        env:
          GOPROXY: "https://proxy.golang.org"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
